### ISSUE TITLE
Convert existing Atlanta BitDevs site to markdown files

### ISSUE THREAD

**Issue by sbddesign** [atlantabitdevs/atlbit.dev#1]
v2.0 Context / Requirements
- [x] Scrape all existing posts from current https://atlantabitdevs.org website
- [x] Add to https://github.com/atlantabitdevs/atlbit.dev
- [x] Turn into markdown files

**Comment by bnonni** [comment]
Command that exists to scrape all pages of a website
```zsh
wget --recursive --no-clobber --page-requisites --html-extension --convert-links --restrict-file-names=windows --domains atlantabitdevs.org --no-parent https://atlantabitdevs.org
```

**Comment by bnonni** [comment]
All pages live here: https://github.com/atlantabitdevs/atlbit.dev
To Do
- [ ] Refine content in [atlbit.dev](https://github.com/atlantabitdevs/atlbit.dev) to only include relevant files (e.g. posts)
- [ ] Convert each into `.md` files

**Comment by bnonni** [comment]
All pages live here: https://github.com/atlantabitdevs/atlbit.dev/tree/master/htmls
All markdowns live here: https://github.com/atlantabitdevs/atlbit.dev/tree/master/markdowns

**Comment by sbddesign** [comment]
# 🔥

LGTM
