### ISSUE TITLE
Simplify markdown files

### ISSUE THREAD

**Issue by sbddesign** [atlantabitdevs/atlbit.dev#3]
Many of the scraped markdown files contain extraneous content, such as the header and footer. All we need is the main content.

Simplify all the markdown files in the `/markdowns` dir. This could be done manually, or with a script. This PR is an example of the expected outcome demonstrated on a single file: https://github.com/atlantabitdevs/atlbit.dev/pull/2

**Comment by gratten** [comment]
1. Strip all content before first # (ie # Bitcoin Socratic Seminar #5)
2. Strip all content after # Post Navigation
3. Add the header and populate it with date, title, type
- for date, I can pull this out of main content where is says published. reformat it to YYYY-MM-DD
- for title, I can use whatever is after first # in main content
- for type, if Socratic Seminar call it an event, anything else call it a post

also, for file name. should I just use the reformatted date as the file name? not sure where we landed on what Nitesh's script will use.

**Comment by sbddesign** [comment]
@gratten
- For date, might need to look at the date of the event. Sorry. The date published might not match event date. Click through the meetup link in the text to find the date the event happened.
- For title, I think you can just use the top level # tag. Usually it will be like "# Bitcoin Socratic Seminar #10: something something"

File name should be something like `YYYY-MM-DD_title_of_event.md`

**Comment by sbddesign** [comment]
Closed in #2 by @gratten
